name: world_news
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  floor: ^1.3.0
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  logger: ^1.1.0
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  reflectable: ^3.0.9

dev_dependencies:
  build_runner: ^2.2.0
  floor_generator: ^1.3.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.3

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/config/l10n
  output_dir: lib/src/core/config/l10n/generated

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
