// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:my_core/src/core/utils/reflector.dart' as prefix0;
import 'package:my_core/src/data/models/api_pagination_model.dart' as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.ModelReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.GenericClassMirrorImpl(
            r'ApiPaginationModel',
            r'.ApiPaginationModel',
            134217735,
            0,
            const prefix0.ModelReflector(),
            const <int>[0, 1, 2, 9, 10, 11],
            const <int>[12, 13, 14, 15, 16, 17, 3, 4, 5, 6, 7, 8, 9],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({data, totalResults, status}) => b
                  ? prefix1.ApiPaginationModel(
                      data: data, status: status, totalResults: totalResults)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.ApiPaginationModel.fromJson(json) : null
            },
            0,
            0,
            const <int>[],
            const <Object>[const prefix0.ModelReflector()],
            null, (o) {
          return o is prefix1.ApiPaginationModel;
        }, const <int>[1], 0),
        r.TypeVariableMirrorImpl(r'MODEL', r'.ApiPaginationModel.MODEL',
            const prefix0.ModelReflector(), -1, 0, <Object>[])
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'data', 84017157, 0,
            const prefix0.ModelReflector(), -1, 1, 2, null, const []),
        r.VariableMirrorImpl(r'totalResults', 67239941, 0,
            const prefix0.ModelReflector(), -1, 3, 3, const <int>[], const []),
        r.VariableMirrorImpl(r'status', 67239941, 0,
            const prefix0.ModelReflector(), -1, 4, 4, const <int>[], const []),
        r.ImplicitGetterMirrorImpl(const prefix0.ModelReflector(), 0, 3),
        r.ImplicitSetterMirrorImpl(const prefix0.ModelReflector(), 0, 4),
        r.ImplicitGetterMirrorImpl(const prefix0.ModelReflector(), 1, 5),
        r.ImplicitSetterMirrorImpl(const prefix0.ModelReflector(), 1, 6),
        r.ImplicitGetterMirrorImpl(const prefix0.ModelReflector(), 2, 7),
        r.ImplicitSetterMirrorImpl(const prefix0.ModelReflector(), 2, 8),
        r.MethodMirrorImpl(
            r'props',
            35651587,
            0,
            -1,
            6,
            7,
            const <int>[5],
            const <int>[],
            const prefix0.ModelReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'', 0, 0, -1, 8, 0, null, const <int>[0, 1, 2],
            const prefix0.ModelReflector(), const []),
        r.MethodMirrorImpl(r'fromJson', 1, 0, -1, 8, 0, null, const <int>[3],
            const prefix0.ModelReflector(), const []),
        r.MethodMirrorImpl(
            r'==',
            2097154,
            -1,
            -1,
            9,
            9,
            const <int>[],
            const <int>[7],
            const prefix0.ModelReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'toString',
            2097154,
            -1,
            -1,
            10,
            10,
            const <int>[],
            const <int>[],
            const prefix0.ModelReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            524290,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[8],
            const prefix0.ModelReflector(),
            const []),
        r.MethodMirrorImpl(
            r'hashCode',
            2097155,
            -1,
            -1,
            11,
            11,
            const <int>[],
            const <int>[],
            const prefix0.ModelReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'runtimeType',
            2097155,
            -1,
            -1,
            12,
            12,
            const <int>[],
            const <int>[],
            const prefix0.ModelReflector(),
            const []),
        r.MethodMirrorImpl(r'stringify', 2097155, -1, -1, 13, 13, const <int>[],
            const <int>[], const prefix0.ModelReflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'data',
            84030470,
            10,
            const prefix0.ModelReflector(),
            -1,
            1,
            2,
            null,
            const [],
            null,
            #data),
        r.ParameterMirrorImpl(
            r'totalResults',
            67253254,
            10,
            const prefix0.ModelReflector(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #totalResults),
        r.ParameterMirrorImpl(
            r'status',
            67253254,
            10,
            const prefix0.ModelReflector(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            #status),
        r.ParameterMirrorImpl(
            r'json',
            151126022,
            11,
            const prefix0.ModelReflector(),
            -1,
            14,
            15,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_data',
            84017254,
            4,
            const prefix0.ModelReflector(),
            -1,
            1,
            2,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_totalResults',
            67240038,
            6,
            const prefix0.ModelReflector(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_status',
            67240038,
            8,
            const prefix0.ModelReflector(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            12,
            const prefix0.ModelReflector(),
            -1,
            16,
            16,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            14,
            const prefix0.ModelReflector(),
            -1,
            17,
            17,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.ApiPaginationModel,
        const r.FakeType(r'dart.core.List<MODEL>'),
        List,
        int,
        String,
        Object,
        const m.TypeValue<List<Object>>().type,
        List,
        const r.FakeType(r'.ApiPaginationModel<MODEL>'),
        bool,
        String,
        int,
        Type,
        bool,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'stringify': (dynamic instance) => instance.stringify,
        r'data': (dynamic instance) => instance.data,
        r'totalResults': (dynamic instance) => instance.totalResults,
        r'status': (dynamic instance) => instance.status,
        r'props': (dynamic instance) => instance.props
      },
      {
        r'data=': (dynamic instance, value) => instance.data = value,
        r'totalResults=': (dynamic instance, value) =>
            instance.totalResults = value,
        r'status=': (dynamic instance, value) => instance.status = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(r'reflectable://0/'),
            const prefix0.ModelReflector(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
