// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:aagel/src/core/utils/reflector.dart' as prefix0;
import 'package:aagel/src/data/models/api_pagination_model.dart' as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.ModelReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.GenericClassMirrorImpl(
            r'ApiPaginationModel',
            r'.ApiPaginationModel',
            134217735,
            0,
            const prefix0.ModelReflector(),
            const <int>[0, 1, 2, 3, 4, 13, 14, 15],
            const <int>[
              16,
              17,
              18,
              19,
              20,
              21,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13
            ],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({data, total, skip, limit}) => b
                  ? prefix1.ApiPaginationModel(
                      data: data, limit: limit, skip: skip, total: total)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.ApiPaginationModel.fromJson(json) : null
            },
            0,
            0,
            const <int>[],
            const <Object>[const prefix0.ModelReflector()],
            null, (o) {
          return o is prefix1.ApiPaginationModel;
        }, const <int>[1], 0),
        r.TypeVariableMirrorImpl(r'MODEL', r'.ApiPaginationModel.MODEL',
            const prefix0.ModelReflector(), -1, 0, <Object>[])
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'data', 84017157, 0,
            const prefix0.ModelReflector(), -1, 1, 2, null, const []),
        r.VariableMirrorImpl(r'total', 67239941, 0,
            const prefix0.ModelReflector(), -1, 3, 3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'skip',
            67141637,
            0,
            const prefix0.ModelReflector(),
            -1,
            -1,
            -1, const <int>[], const []),
        r.VariableMirrorImpl(r'limit', 67239941, 0,
            const prefix0.ModelReflector(), -1, 3, 3, const <int>[], const []),
        r.MethodMirrorImpl(
            r'reflectObject',
            524290,
            0,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[0],
            const prefix0.ModelReflector(),
            const []),
        r.ImplicitGetterMirrorImpl(const prefix0.ModelReflector(), 0, 5),
        r.ImplicitSetterMirrorImpl(const prefix0.ModelReflector(), 0, 6),
        r.ImplicitGetterMirrorImpl(const prefix0.ModelReflector(), 1, 7),
        r.ImplicitSetterMirrorImpl(const prefix0.ModelReflector(), 1, 8),
        r.ImplicitGetterMirrorImpl(const prefix0.ModelReflector(), 2, 9),
        r.ImplicitSetterMirrorImpl(const prefix0.ModelReflector(), 2, 10),
        r.ImplicitGetterMirrorImpl(const prefix0.ModelReflector(), 3, 11),
        r.ImplicitSetterMirrorImpl(const prefix0.ModelReflector(), 3, 12),
        r.MethodMirrorImpl(
            r'props',
            35651587,
            0,
            -1,
            5,
            6,
            const <int>[4],
            const <int>[],
            const prefix0.ModelReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'', 0, 0, -1, 7, 0, null, const <int>[1, 2, 3, 4],
            const prefix0.ModelReflector(), const []),
        r.MethodMirrorImpl(r'fromJson', 1, 0, -1, 7, 0, null, const <int>[5],
            const prefix0.ModelReflector(), const []),
        r.MethodMirrorImpl(
            r'==',
            2097154,
            -1,
            -1,
            8,
            8,
            const <int>[],
            const <int>[10],
            const prefix0.ModelReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'toString',
            2097154,
            -1,
            -1,
            9,
            9,
            const <int>[],
            const <int>[],
            const prefix0.ModelReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            524290,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[11],
            const prefix0.ModelReflector(),
            const []),
        r.MethodMirrorImpl(
            r'hashCode',
            2097155,
            -1,
            -1,
            10,
            10,
            const <int>[],
            const <int>[],
            const prefix0.ModelReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'runtimeType',
            2097155,
            -1,
            -1,
            11,
            11,
            const <int>[],
            const <int>[],
            const prefix0.ModelReflector(),
            const []),
        r.MethodMirrorImpl(r'stringify', 2097155, -1, -1, 12, 12, const <int>[],
            const <int>[], const prefix0.ModelReflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'json',
            151126022,
            4,
            const prefix0.ModelReflector(),
            -1,
            13,
            14,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'data',
            84030470,
            14,
            const prefix0.ModelReflector(),
            -1,
            1,
            2,
            null,
            const [],
            null,
            #data),
        r.ParameterMirrorImpl(
            r'total',
            67253254,
            14,
            const prefix0.ModelReflector(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #total),
        r.ParameterMirrorImpl(
            r'skip',
            67154950,
            14,
            const prefix0.ModelReflector(),
            -1,
            -1,
            -1,
            const <int>[],
            const [],
            null,
            #skip),
        r.ParameterMirrorImpl(
            r'limit',
            67253254,
            14,
            const prefix0.ModelReflector(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #limit),
        r.ParameterMirrorImpl(
            r'json',
            151126022,
            15,
            const prefix0.ModelReflector(),
            -1,
            13,
            14,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_data',
            84017254,
            6,
            const prefix0.ModelReflector(),
            -1,
            1,
            2,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_total',
            67240038,
            8,
            const prefix0.ModelReflector(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_skip',
            67141734,
            10,
            const prefix0.ModelReflector(),
            -1,
            -1,
            -1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_limit',
            67240038,
            12,
            const prefix0.ModelReflector(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            16,
            const prefix0.ModelReflector(),
            -1,
            15,
            15,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            18,
            const prefix0.ModelReflector(),
            -1,
            16,
            16,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.ApiPaginationModel,
        const r.FakeType(r'dart.core.List<MODEL>'),
        List,
        int,
        Object,
        const m.TypeValue<List<Object>>().type,
        List,
        const r.FakeType(r'.ApiPaginationModel<MODEL>'),
        bool,
        String,
        int,
        Type,
        bool,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'stringify': (dynamic instance) => instance.stringify,
        r'reflectObject': (dynamic instance) => instance.reflectObject,
        r'data': (dynamic instance) => instance.data,
        r'total': (dynamic instance) => instance.total,
        r'skip': (dynamic instance) => instance.skip,
        r'limit': (dynamic instance) => instance.limit,
        r'props': (dynamic instance) => instance.props
      },
      {
        r'data=': (dynamic instance, value) => instance.data = value,
        r'total=': (dynamic instance, value) => instance.total = value,
        r'skip=': (dynamic instance, value) => instance.skip = value,
        r'limit=': (dynamic instance, value) => instance.limit = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse(r'reflectable://0/'),
            const prefix0.ModelReflector(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
